### ISSUE TITLE
Volt site CMS

### ISSUE THREAD

**Issue by bubnenkoff** [VoltLang/Volta#11]
I would like to suggest migrate Volt site to our new CMS that already in use at dlang.ru 
We just end very huge refactoring of it. It's very powerfull CMS based in .NET MVC. Maybe it's not best stack of technologies, but it's enough good.

The CMS is now private project. Very soon we will move it's to public. It's can be very good for creation community of about Volta, like was at D1 time with Dsource.org

I can give distribution of our CMS for free (except sources -- I can distribute them due to license issues -- it's not only my project). So you can look at it. And if you like, I would also happy to make Volta site more usable.

Very soon we will end work on new default theme, and site would look move better then now.

**Comment by bhelyer** [comment]
Thank you for the offer, but we don't need much out of our website at the moment. We might consider it later down the road. ^^;
