### ISSUE TITLE
Safe int

### ISSUE THREAD

**Issue by bubnenkoff** [VoltLang/Volta#12]
As I wrote before I am interesting in Volta as more high-level language then D. So I hope to see in it's by default things like safe int like http://code.dlang.org/packages/safeint

**Comment by bhelyer** [comment]
Interesting, I wonder if it could be generalised to have an invalid type for all types.

**Comment by Wallbraker** [comment]
Volt is still a system-level programming language so I don't see the need for those features directly in the language. Having features in the language that make it possible to implement those features are on the other hand.
