### ISSUE TITLE
Change logical operators to word

### ISSUE THREAD

**Issue by bubnenkoff** [VoltLang/Volta#15]
I really do not see any benefits in using operators like: `&&` `||` and so on. It's much easier to read code that use normal words like: AND OR and so on.

`if (a = 1 OR b =2)` look better then `if (a = 1 || b =2)`

**Comment by Wallbraker** [comment]
Since Volt is a C type language we will keep the symbolic operator, also since all other keywords are uncapitalized capitalized ones would look out of place.
