### ISSUE TITLE
is Volt development stopped ?

### ISSUE THREAD

**Issue by ffred** [VoltLang/Volta#58]
Hi,
just discovered Volt and it look nice, but every date I can see seems old now. is the development on a pause or stopped..?

**Comment by Wallbraker** [comment]
As much as I don't want to say it, it's most definitely paused. But I'm hoping I can find time and energy to work on it more. I do use Volt in various little projects here and there, and it works well enough for me. Which makes it harder to focus more on it, since it works well enough for me.

**Comment by ffred** [comment]
ok, thanks for replying...
