### ISSUE TITLE
-Lgc library not found

### ISSUE THREAD

**Issue by perfaram** [VoltLang/Volta#6]
I followed instructions for OS X, I'm on Yosemite 10.10.4.
DMD is in the path & works, just like llvm-config.
`make` seems to succeed, but `make run` outputs : 
```
[stripped]
attributes #0 = { noreturn nounwind }
attributes #1 = { uwtable }
ld: library not found for -lgc
clang: error: linker command failed with exit code 1 (use -v to see invocation)
  RUN    a.out
make: ./a.out: No such file or directory
make: [run] Error 1 (ignored)
```
Any idea ? I guess -lgc is a garbage collection library, but why is it missing ?

**Comment by bhelyer** [comment]
GC is the [Boehm garbage collector][1]. It's probably not installed by default with OS X, so it really should be mentioned on our readme. I don't use OS X myself, so I can't give you specific installation instructions but hopefully an Apple-using compatriot will be along if you need specifics.

[1]:http://www.hboehm.info/gc/

**Comment by Wallbraker** [comment]
I used these commands to create a working libgc.a.

```bash
curl http://www.hboehm.info/gc/gc_source/gc-7.4.2.tar.gz -o gc-7.4.2.tar.gz
tar xfv gc-7.4.2.tar.gz 
cd gc-7.4.2
git clone git://github.com/ivmai/libatomic_ops.git
./configure 
make -j9
cp .libs/libgc.a <somewhere where volta can find it>
```

I personally just install it in a 'lib' folder and point volta to it with:
```
-L
<path>/lib
```

**Comment by perfaram** [comment]
OK ! Now it finds the GC lib (at least, doesn't complain about not finding it).
BUT : I get `make: [run] Error 42 (ignored)`. What is it ?

**Comment by Dav1dde** [comment]
This means it works! `make run` compiles and runs the [test.volt](https://github.com/VoltLang/Volta/blob/master/test/test.volt) file. You now have a fully functional Volt compiler! :)

**Comment by perfaram** [comment]
42... should've guessed ! Thanks again !

**Comment by perfaram** [comment]
One more thing : how do I build it manually ?

**Comment by Wallbraker** [comment]
Add this file as volt.conf next the binary (proably in the Volta repo) http://vp.dav1d.de/gxq9I and edit if needed. With that config file you will need to checkout the Watt repo next to the Volta repo and then build it.

We hope to add more documentation and howto's in the coming weeks.

**Comment by Wallbraker** [comment]
You can join us on IRC in #volt on Freenode. And also feel free to checkout our Trello board for some of the plans: https://trello.com/b/tnuM8Sjy/volt

**Comment by Dav1dde** [comment]
One more thing which isn't documentated, how to build Tesla and Watt:

```
VOLT=/path/to/volt/binary/volt make
```

You need an environment variable called `VOLT` to link to the ready Volt binary, for me it is: `VOLT=../Volta/volt`.

**Comment by Wallbraker** [comment]
Oh yeah, that or having the volt binary on the path.

**Comment by perfaram** [comment]
OK, will see that this evening. BTW, #7 .

**Comment by perfaram** [comment]
OK, everything seems good, everything works, everything compiles, everything is beautiful :smile:
