### ISSUE TITLE
Volt is BROKEN and should be fixed

### ISSUE THREAD

**Issue by ghost** [VoltLang/Volta#60]
@Wallbraker I can't compile simple program:

**input:**

```volt
import watt.io;

fn main() i32
{
    writeln("hello, world");
    return 0;
}
```

**output:**

```
main.volt:1:1: error: can't find module 'core.compiler.defaultsymbols'.
/Users/t0md3an/Desktop/Volta/lib/src/volta/postparse/importresolver.d:90
```

**Comment by t0md3an** [comment]
@Wallbraker What should I do now with this? I just want to try this language, but I can't because of this!

**Comment by t0md3an** [comment]
@Wallbraker

**Comment by t0md3an** [comment]
@Wallbraker Said me how to fix this, how to make Volt work. Over two days I trying to check Volt.

**Comment by bhelyer** [comment]
Hi ghost,
Apologies that it took so long for this to get a reply. If this is still an active issue for you, please let us know and we'll reopen and try to help you.
